apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "orc.fullname" . }}-manager-rolebinding
  labels:
    {{- include "orc.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "orc.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "orc.fullname" . }}-controller-manager
  namespace: {{ include "orc.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "orc.fullname" . }}-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "orc.fullname" . }}-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: {{ include "orc.fullname" . }}-controller-manager
  namespace: {{ include "orc.namespace" . }}