apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "orc.fullname" . }}-leader-election-rolebinding
  namespace: {{ include "orc.namespace" . }}
  labels:
    {{- include "orc.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "orc.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "orc.fullname" . }}-controller-manager
  namespace: {{ include "orc.namespace" . }}