apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "orc.fullname" . }}-controller-manager
  namespace: {{ include "orc.namespace" . }}
  labels:
    {{- include "orc.labels" . | nindent 4 }}