apiVersion: v1
kind: Service
metadata:
  name: {{ include "orc.fullname" . }}-controller-manager-metrics-service
  namespace: {{ include "orc.namespace" . }}
  labels:
    {{- include "orc.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "orc.selectorLabels" . | nindent 4 }}